name: 'CI'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Step 1'
      run: |
        cd Step1-MakeFile
        make all .
    - name: 'Step 2'
      run: |
        cd Step2-CMake
        mkdir BuildCI
        cd BuildCI
        cmake ..
        cmake --build .
