name: 'CI'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Packages'
      run: sudo apt update && sudo apt install libcunit1-dev gcovr && sudo apt-get install libsdl2-dev
    - name: 'Step 1'
      run: |
      	cd Step1-MakeFile
      	mkdir BuildCI
      	cd BuildCI
      	cmake ..
      	make
