name: 'CI'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Packages'
      run: |
        sudo apt update
        sudo apt install libcunit1-dev gcovr
        sudo apt-get install libsdl2-dev
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu
    - name: 'Step 1'
      run: |
        cd Step1-MakeFile
        make all .
    - name: 'Step 2'
      run: |
        cd Step2-CMake
        mkdir BuildCI
        cd BuildCI
        cmake ..
        cmake --build .
    - name: 'SDL'
      run: |
        cd Step4-SDL
        mkdir BuildCI
        cd BuildCI
        cmake ..
        cmake --build .
