name: 'CI'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Unit Tests'
      run: |
        cd Unit_Tests
        mkdir BuildCI
        cd BuildCI
        cmake ..
        cmake --build .
